name: Build Electron App

# mainブランチにプッシュされた時にこの処理を自動実行する
on:
  push:
    branches: [ main ]

jobs:
  build:
    # macOSの最新版が動く仮想マシンで実行する
    runs-on: macos-latest

    steps:
      # 1. リポジトリのコードを仮想マシンにコピーする
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js環境をセットアップする
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # プロジェクトに合わせたバージョン

      # 3. 必要なモジュールをインストールする
      - name: Install dependencies
        run: npm install

      # 4. アプリをビルドする (Mac用の.dmgファイルが作られる)
      - name: Build application
        run: npm run build

      # 5. 完成したファイルをダウンロードできるように保存する
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: time-q-mac-build
          path: dist/